export const GALLERY_ITEMS = [
  {
    id: 1,
    label: 'Mercedes-Benz C-Klasa',
    category: 'Przed / Po',
    hint: 'Korekta lakieru + powłoka ceramiczna',
    image: '/mercedes-C-klasa-blue-ppf.png',
    imageAlt: 'Mercedes-Benz C-Klasa po korekcie lakieru i nałożeniu powłoki ceramicznej',
    assetStatus: 'confirmed',
  },
  {
    id: 2,
    label: 'BMW Seria 5',
    category: 'Przed / Po',
    hint: 'Dekontaminacja + wosk twardy',
    image: '/bmw-5-series-lb.png',
    imageAlt: 'BMW Seria 5 po dekontaminacji i nałożeniu wosku twardego',
    assetStatus: 'confirmed',
  },
  {
    id: 3,
    label: 'Audi Q7',
    category: 'Przed / Po',
    hint: 'Pełny detailing zewnętrzny',
    image: '/Audi Q7 in spacious garage.png',
    imageAlt: 'Audi Q7 po pełnym detailingu zewnętrznym',
    assetStatus: 'confirmed',
  },
  {
    id: 4,
    label: 'Porsche 911',
    category: 'Powłoka ceramiczna',
    hint: 'Nanoceramika 3-warstwowa',
    image: '/White Porsche 911 in garage詳細.png',
    imageAlt: 'Porsche 911 z nanoceramiką 3-warstwową',
    assetStatus: 'confirmed',
  },
  {
    id: 5,
    label: 'Range Rover Sport',
    category: 'Powłoka ceramiczna',
    hint: 'Powłoka ceramiczna + ochrona felg',
    image: '/range-rover-sport-brown.png',
    imageAlt: 'Range Rover Sport z powłoką ceramiczną i ochroną felg',
    assetStatus: 'confirmed',
  },
  {
    id: 6,
    label: 'Volkswagen Golf GTI',
    category: 'Folia PPF',
    hint: 'PPF na strefie uderzeń kamieni',
    image: '/golf-gti-czerwony-ppf.png',
    imageAlt: 'Volkswagen Golf GTI z folią PPF na strefie uderzeń kamieni',
    assetStatus: 'confirmed',
  },
  {
    id: 7,
    label: 'Tesla Model 3',
    category: 'Folia PPF',
    hint: 'PPF pełne nadwozie + dach',
    image: '/tesla-model3.png',
    imageAlt: 'Tesla Model 3 z folią PPF na pełnym nadwoziu i dachu',
    assetStatus: 'confirmed',
  },
 
]
